DEBUG	2023-01-05 11:14:58,565	[remote_connection.py:308]	POST http://127.0.0.1:4723/wd/hub/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"platformName": "Android", "appium:deviceName": "127.0.0.1:21503", "appium:platformVersion": "7.1.2", "appium:appPackage": "com.tal.kaoyan", "appium:appActivity": "ui.activity.SplashActivity", "appium:noReset": false, "appium:unicodeKeyboard": true, "appium:resetKeyboard": true, "appium:automationName": "uiautomator2"}}}
DEBUG	2023-01-05 11:14:58,566	[connectionpool.py:232]	Starting new HTTP connection (1): 127.0.0.1:4723
DEBUG	2023-01-05 11:15:00,575	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 11:15:00,576	[connectionpool.py:813]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002AD43E2E6C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 11:15:00,577	[connectionpool.py:232]	Starting new HTTP connection (2): 127.0.0.1:4723
DEBUG	2023-01-05 11:15:02,580	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 11:15:02,580	[connectionpool.py:813]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002AD43E56088>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 11:15:02,580	[connectionpool.py:232]	Starting new HTTP connection (3): 127.0.0.1:4723
DEBUG	2023-01-05 11:15:04,583	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 11:15:04,583	[connectionpool.py:813]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002AD43E56848>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 11:15:04,583	[connectionpool.py:232]	Starting new HTTP connection (4): 127.0.0.1:4723
DEBUG	2023-01-05 11:15:20,583	[remote_connection.py:308]	POST http://127.0.0.1:4723/wd/hub/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"platformName": "Android", "appium:deviceName": "127.0.0.1:21503", "appium:platformVersion": "7.1.2", "appium:appPackage": "com.tal.kaoyan", "appium:appActivity": "ui.activity.SplashActivity", "appium:noReset": false, "appium:unicodeKeyboard": true, "appium:resetKeyboard": true, "appium:automationName": "uiautomator2"}}}
DEBUG	2023-01-05 11:15:20,584	[connectionpool.py:232]	Starting new HTTP connection (1): 127.0.0.1:4723
DEBUG	2023-01-05 11:15:22,589	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 11:15:22,589	[connectionpool.py:813]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026BC3A0E588>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 11:15:22,589	[connectionpool.py:232]	Starting new HTTP connection (2): 127.0.0.1:4723
DEBUG	2023-01-05 11:15:24,592	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 11:15:24,592	[connectionpool.py:813]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026BC3A2EF08>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 11:15:24,592	[connectionpool.py:232]	Starting new HTTP connection (3): 127.0.0.1:4723
DEBUG	2023-01-05 11:15:26,595	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 11:15:26,595	[connectionpool.py:813]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026BC3A37748>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 11:15:26,595	[connectionpool.py:232]	Starting new HTTP connection (4): 127.0.0.1:4723
DEBUG	2023-01-05 11:15:54,371	[remote_connection.py:308]	POST http://127.0.0.1:4723/wd/hub/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"platformName": "Android", "appium:deviceName": "127.0.0.1:21503", "appium:platformVersion": "7.1.2", "appium:appPackage": "com.tal.kaoyan", "appium:appActivity": "ui.activity.SplashActivity", "appium:noReset": false, "appium:unicodeKeyboard": true, "appium:resetKeyboard": true, "appium:automationName": "uiautomator2"}}}
DEBUG	2023-01-05 11:15:54,372	[connectionpool.py:232]	Starting new HTTP connection (1): 127.0.0.1:4723
DEBUG	2023-01-05 11:15:56,377	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 11:15:56,378	[connectionpool.py:813]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027DB7CCC3C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 11:15:56,379	[connectionpool.py:232]	Starting new HTTP connection (2): 127.0.0.1:4723
DEBUG	2023-01-05 11:15:58,383	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 11:15:58,383	[connectionpool.py:813]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027DB7CEED48>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 11:15:58,383	[connectionpool.py:232]	Starting new HTTP connection (3): 127.0.0.1:4723
DEBUG	2023-01-05 11:16:00,385	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 11:16:00,385	[connectionpool.py:813]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027DB7CF7548>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 11:16:00,385	[connectionpool.py:232]	Starting new HTTP connection (4): 127.0.0.1:4723
DEBUG	2023-01-05 11:30:08,920	[remote_connection.py:308]	POST http://127.0.0.1:4723/wd/hub/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"platformName": "Android", "appium:deviceName": "127.0.0.1:21503", "appium:platformVersion": "7.1.2", "appium:appPackage": "com.tal.kaoyan", "appium:appActivity": "ui.activity.SplashActivity", "appium:noReset": false, "appium:unicodeKeyboard": true, "appium:resetKeyboard": true, "appium:automationName": "uiautomator2"}}}
DEBUG	2023-01-05 11:30:08,921	[connectionpool.py:232]	Starting new HTTP connection (1): 127.0.0.1:4723
DEBUG	2023-01-05 11:30:10,926	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 11:30:10,926	[connectionpool.py:813]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C9FE6AD608>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 11:30:10,926	[connectionpool.py:232]	Starting new HTTP connection (2): 127.0.0.1:4723
DEBUG	2023-01-05 11:30:12,929	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 11:30:12,929	[connectionpool.py:813]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C9FE6D7048>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 11:30:12,929	[connectionpool.py:232]	Starting new HTTP connection (3): 127.0.0.1:4723
DEBUG	2023-01-05 11:30:14,932	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 11:30:14,932	[connectionpool.py:813]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C9FE6D77C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 11:30:14,932	[connectionpool.py:232]	Starting new HTTP connection (4): 127.0.0.1:4723
DEBUG	2023-01-05 11:37:25,696	[remote_connection.py:308]	POST http://127.0.0.1:4723/wd/hub/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"platformName": "Android", "appium:deviceName": "127.0.0.1:21503", "appium:platformVersion": "7.1.2", "appium:appPackage": "com.tal.kaoyan", "appium:appActivity": "ui.activity.SplashActivity", "appium:noReset": false, "appium:unicodeKeyboard": true, "appium:resetKeyboard": true, "appium:automationName": "uiautomator2"}}}
DEBUG	2023-01-05 11:37:25,696	[connectionpool.py:232]	Starting new HTTP connection (1): 127.0.0.1:4723
DEBUG	2023-01-05 11:37:27,701	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 11:37:27,701	[connectionpool.py:813]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002071B7DD288>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 11:37:27,701	[connectionpool.py:232]	Starting new HTTP connection (2): 127.0.0.1:4723
DEBUG	2023-01-05 11:37:29,704	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 11:37:29,704	[connectionpool.py:813]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002071B7FFE08>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 11:37:29,704	[connectionpool.py:232]	Starting new HTTP connection (3): 127.0.0.1:4723
DEBUG	2023-01-05 11:37:31,712	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 11:37:31,712	[connectionpool.py:813]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002071B8096C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 11:37:31,712	[connectionpool.py:232]	Starting new HTTP connection (4): 127.0.0.1:4723
DEBUG	2023-01-05 13:23:48,645	[remote_connection.py:308]	POST http://127.0.0.1:4723/wd/hub/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"platformName": "Android", "appium:deviceName": "127.0.0.1:21503", "appium:platformVersion": "7.1.2", "appium:appPackage": "com.tal.kaoyan", "appium:appActivity": "ui.activity.SplashActivity", "appium:noReset": false, "appium:unicodeKeyboard": true, "appium:resetKeyboard": true, "appium:automationName": "uiautomator2"}}}
DEBUG	2023-01-05 13:23:48,646	[connectionpool.py:232]	Starting new HTTP connection (1): 127.0.0.1:4723
DEBUG	2023-01-05 13:23:50,651	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 13:23:50,651	[connectionpool.py:813]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F11019D708>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 13:23:50,651	[connectionpool.py:232]	Starting new HTTP connection (2): 127.0.0.1:4723
DEBUG	2023-01-05 13:23:52,654	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 13:23:52,655	[connectionpool.py:813]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F1101C40C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 13:23:52,656	[connectionpool.py:232]	Starting new HTTP connection (3): 127.0.0.1:4723
DEBUG	2023-01-05 13:23:54,658	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 13:23:54,658	[connectionpool.py:813]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F1101C48C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 13:23:54,658	[connectionpool.py:232]	Starting new HTTP connection (4): 127.0.0.1:4723
DEBUG	2023-01-05 14:26:56,616	[remote_connection.py:308]	POST http://127.0.0.1:4723/wd/hub/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"platformName": "Android", "appium:deviceName": "127.0.0.1:21503", "appium:platformVersion": "7.1.2", "appium:appPackage": "com.tal.kaoyan", "appium:appActivity": "ui.activity.SplashActivity", "appium:noReset": false, "appium:unicodeKeyboard": true, "appium:resetKeyboard": true, "appium:automationName": "uiautomator2"}}}
DEBUG	2023-01-05 14:26:56,616	[connectionpool.py:232]	Starting new HTTP connection (1): 127.0.0.1:4723
DEBUG	2023-01-05 14:26:58,622	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:26:58,622	[connectionpool.py:813]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8BF13B808>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:26:58,622	[connectionpool.py:232]	Starting new HTTP connection (2): 127.0.0.1:4723
DEBUG	2023-01-05 14:27:00,625	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:27:00,626	[connectionpool.py:813]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8BF164148>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:27:00,626	[connectionpool.py:232]	Starting new HTTP connection (3): 127.0.0.1:4723
DEBUG	2023-01-05 14:27:02,629	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:27:02,629	[connectionpool.py:813]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8BF1649C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:27:02,629	[connectionpool.py:232]	Starting new HTTP connection (4): 127.0.0.1:4723
DEBUG	2023-01-05 14:33:42,020	[remote_connection.py:308]	POST http://127.0.0.1:4723/wd/hub/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"platformName": "Android", "appium:deviceName": "127.0.0.1:21503", "appium:platformVersion": "7.1.2", "appium:appPackage": "com.tal.kaoyan", "appium:appActivity": "ui.activity.SplashActivity", "appium:noReset": false, "appium:unicodeKeyboard": true, "appium:resetKeyboard": true, "appium:automationName": "uiautomator2"}}}
DEBUG	2023-01-05 14:33:42,021	[connectionpool.py:232]	Starting new HTTP connection (1): 127.0.0.1:4723
DEBUG	2023-01-05 14:33:44,025	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:33:44,025	[connectionpool.py:813]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000011E9DCED488>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:33:44,025	[connectionpool.py:232]	Starting new HTTP connection (2): 127.0.0.1:4723
DEBUG	2023-01-05 14:33:46,029	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:33:46,029	[connectionpool.py:813]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000011E9DD0FD88>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:33:46,030	[connectionpool.py:232]	Starting new HTTP connection (3): 127.0.0.1:4723
DEBUG	2023-01-05 14:33:48,036	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:33:48,036	[connectionpool.py:813]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000011E9DD18648>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:33:48,036	[connectionpool.py:232]	Starting new HTTP connection (4): 127.0.0.1:4723
DEBUG	2023-01-05 14:34:03,577	[remote_connection.py:308]	POST http://127.0.0.1:4723/wd/hub/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"platformName": "Android", "appium:deviceName": "127.0.0.1:21503", "appium:platformVersion": "7.1.2", "appium:appPackage": "com.tal.kaoyan", "appium:appActivity": "ui.activity.SplashActivity", "appium:noReset": false, "appium:unicodeKeyboard": true, "appium:resetKeyboard": true, "appium:automationName": "uiautomator2"}}}
DEBUG	2023-01-05 14:34:03,577	[connectionpool.py:232]	Starting new HTTP connection (1): 127.0.0.1:4723
DEBUG	2023-01-05 14:34:05,583	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:34:05,584	[connectionpool.py:813]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000014EFED3D708>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:34:05,585	[connectionpool.py:232]	Starting new HTTP connection (2): 127.0.0.1:4723
DEBUG	2023-01-05 14:34:07,589	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:34:07,589	[connectionpool.py:813]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000014EFED65088>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:34:07,589	[connectionpool.py:232]	Starting new HTTP connection (3): 127.0.0.1:4723
DEBUG	2023-01-05 14:34:09,592	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:34:09,593	[connectionpool.py:813]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000014EFED65908>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:34:09,594	[connectionpool.py:232]	Starting new HTTP connection (4): 127.0.0.1:4723
DEBUG	2023-01-05 14:34:42,937	[remote_connection.py:308]	POST http://127.0.0.1:4723/wd/hub/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"platformName": "Android", "appium:deviceName": "127.0.0.1:21503", "appium:platformVersion": "7.1.2", "appium:appPackage": "com.tal.kaoyan", "appium:appActivity": "ui.activity.SplashActivity", "appium:noReset": false, "appium:unicodeKeyboard": true, "appium:resetKeyboard": true, "appium:automationName": "uiautomator2"}}}
DEBUG	2023-01-05 14:34:42,938	[connectionpool.py:232]	Starting new HTTP connection (1): 127.0.0.1:4723
DEBUG	2023-01-05 14:34:44,943	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:34:44,944	[connectionpool.py:813]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028160A7D348>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:34:44,944	[connectionpool.py:232]	Starting new HTTP connection (2): 127.0.0.1:4723
DEBUG	2023-01-05 14:34:46,949	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:34:46,950	[connectionpool.py:813]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028160AA7048>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:34:46,951	[connectionpool.py:232]	Starting new HTTP connection (3): 127.0.0.1:4723
DEBUG	2023-01-05 14:34:48,955	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:34:48,956	[connectionpool.py:813]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028160AA7788>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:34:48,957	[connectionpool.py:232]	Starting new HTTP connection (4): 127.0.0.1:4723
DEBUG	2023-01-05 14:35:00,322	[remote_connection.py:308]	POST http://127.0.0.1:4723/wd/hub/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"platformName": "Android", "appium:deviceName": "127.0.0.1:21503", "appium:platformVersion": "7.1.2", "appium:appPackage": "com.tal.kaoyan", "appium:appActivity": "ui.activity.SplashActivity", "appium:noReset": false, "appium:unicodeKeyboard": true, "appium:resetKeyboard": true, "appium:automationName": "uiautomator2"}}}
DEBUG	2023-01-05 14:35:00,323	[connectionpool.py:232]	Starting new HTTP connection (1): 127.0.0.1:4723
DEBUG	2023-01-05 14:35:02,330	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:35:02,331	[connectionpool.py:813]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B84E16D288>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:35:02,331	[connectionpool.py:232]	Starting new HTTP connection (2): 127.0.0.1:4723
DEBUG	2023-01-05 14:35:04,334	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:35:04,334	[connectionpool.py:813]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B84E18BC08>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:35:04,334	[connectionpool.py:232]	Starting new HTTP connection (3): 127.0.0.1:4723
DEBUG	2023-01-05 14:35:06,337	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:35:06,339	[connectionpool.py:813]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B84E1A5348>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:35:06,340	[connectionpool.py:232]	Starting new HTTP connection (4): 127.0.0.1:4723
DEBUG	2023-01-05 14:35:50,130	[remote_connection.py:308]	POST http://127.0.0.1:4723/wd/hub/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"platformName": "Android", "appium:deviceName": "127.0.0.1:21503", "appium:platformVersion": "7.1.2", "appium:appPackage": "com.tal.kaoyan", "appium:appActivity": "ui.activity.SplashActivity", "appium:noReset": false, "appium:unicodeKeyboard": true, "appium:resetKeyboard": true, "appium:automationName": "uiautomator2"}}}
DEBUG	2023-01-05 14:35:50,130	[connectionpool.py:232]	Starting new HTTP connection (1): 127.0.0.1:4723
DEBUG	2023-01-05 14:35:52,137	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:35:52,137	[connectionpool.py:813]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002839EB6D4C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:35:52,137	[connectionpool.py:232]	Starting new HTTP connection (2): 127.0.0.1:4723
DEBUG	2023-01-05 14:35:54,141	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:35:54,141	[connectionpool.py:813]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002839EB8FE08>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:35:54,141	[connectionpool.py:232]	Starting new HTTP connection (3): 127.0.0.1:4723
DEBUG	2023-01-05 14:35:56,143	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:35:56,143	[connectionpool.py:813]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002839EB986C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:35:56,143	[connectionpool.py:232]	Starting new HTTP connection (4): 127.0.0.1:4723
DEBUG	2023-01-05 14:35:58,729	[remote_connection.py:308]	POST http://127.0.0.1:4723/wd/hub/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"platformName": "Android", "appium:deviceName": "127.0.0.1:21503", "appium:platformVersion": "7.1.2", "appium:appPackage": "com.tal.kaoyan", "appium:appActivity": "ui.activity.SplashActivity", "appium:noReset": false, "appium:unicodeKeyboard": true, "appium:resetKeyboard": true, "appium:automationName": "uiautomator2"}}}
DEBUG	2023-01-05 14:35:58,729	[connectionpool.py:232]	Starting new HTTP connection (1): 127.0.0.1:4723
DEBUG	2023-01-05 14:36:00,738	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:36:00,738	[connectionpool.py:813]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000299F18552C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:36:00,738	[connectionpool.py:232]	Starting new HTTP connection (2): 127.0.0.1:4723
DEBUG	2023-01-05 14:36:02,740	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:36:02,740	[connectionpool.py:813]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000299F186FC08>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:36:02,740	[connectionpool.py:232]	Starting new HTTP connection (3): 127.0.0.1:4723
DEBUG	2023-01-05 14:36:04,744	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:36:04,744	[connectionpool.py:813]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000299F18884C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:36:04,744	[connectionpool.py:232]	Starting new HTTP connection (4): 127.0.0.1:4723
DEBUG	2023-01-05 14:36:09,463	[remote_connection.py:308]	POST http://127.0.0.1:4723/wd/hub/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"platformName": "Android", "appium:deviceName": "127.0.0.1:21503", "appium:platformVersion": "7.1.2", "appium:appPackage": "com.tal.kaoyan", "appium:appActivity": "ui.activity.SplashActivity", "appium:noReset": false, "appium:unicodeKeyboard": true, "appium:resetKeyboard": true, "appium:automationName": "uiautomator2"}}}
DEBUG	2023-01-05 14:36:09,464	[connectionpool.py:232]	Starting new HTTP connection (1): 127.0.0.1:4723
DEBUG	2023-01-05 14:36:11,470	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:36:11,470	[connectionpool.py:813]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002031D7AD4C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:36:11,470	[connectionpool.py:232]	Starting new HTTP connection (2): 127.0.0.1:4723
DEBUG	2023-01-05 14:36:13,474	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:36:13,474	[connectionpool.py:813]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002031D7CED48>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:36:13,474	[connectionpool.py:232]	Starting new HTTP connection (3): 127.0.0.1:4723
DEBUG	2023-01-05 14:36:15,481	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:36:15,481	[connectionpool.py:813]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002031D7D7608>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:36:15,481	[connectionpool.py:232]	Starting new HTTP connection (4): 127.0.0.1:4723
DEBUG	2023-01-05 14:36:43,387	[remote_connection.py:308]	POST http://127.0.0.1:4723/wd/hub/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"platformName": "Android", "appium:deviceName": "127.0.0.1:21503", "appium:platformVersion": "7.1.2", "appium:appPackage": "com.tal.kaoyan", "appium:appActivity": "ui.activity.SplashActivity", "appium:noReset": false, "appium:unicodeKeyboard": true, "appium:resetKeyboard": true, "appium:automationName": "uiautomator2"}}}
DEBUG	2023-01-05 14:36:43,387	[connectionpool.py:232]	Starting new HTTP connection (1): 127.0.0.1:4723
DEBUG	2023-01-05 14:36:45,393	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:36:45,393	[connectionpool.py:813]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002D14E3F4388>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:36:45,393	[connectionpool.py:232]	Starting new HTTP connection (2): 127.0.0.1:4723
DEBUG	2023-01-05 14:36:47,394	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:36:47,395	[connectionpool.py:813]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002D14E40EC48>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:36:47,395	[connectionpool.py:232]	Starting new HTTP connection (3): 127.0.0.1:4723
DEBUG	2023-01-05 14:36:49,399	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:36:49,399	[connectionpool.py:813]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002D14E417508>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:36:49,399	[connectionpool.py:232]	Starting new HTTP connection (4): 127.0.0.1:4723
DEBUG	2023-01-05 14:40:25,820	[remote_connection.py:308]	POST http://127.0.0.1:4723/wd/hub/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"platformName": "Android", "appium:deviceName": "127.0.0.1:21503", "appium:platformVersion": "7.1.2", "appium:appPackage": "com.tal.kaoyan", "appium:appActivity": "ui.activity.SplashActivity", "appium:noReset": false, "appium:unicodeKeyboard": true, "appium:resetKeyboard": true, "appium:automationName": "uiautomator2"}}}
DEBUG	2023-01-05 14:40:25,821	[connectionpool.py:232]	Starting new HTTP connection (1): 127.0.0.1:4723
DEBUG	2023-01-05 14:40:27,825	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:40:27,826	[connectionpool.py:813]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002DAC7FD6288>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:40:27,827	[connectionpool.py:232]	Starting new HTTP connection (2): 127.0.0.1:4723
DEBUG	2023-01-05 14:40:29,831	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:40:29,831	[connectionpool.py:813]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002DAC7FEEB88>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:40:29,832	[connectionpool.py:232]	Starting new HTTP connection (3): 127.0.0.1:4723
DEBUG	2023-01-05 14:40:31,835	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:40:31,836	[connectionpool.py:813]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002DAC7FF7448>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:40:31,837	[connectionpool.py:232]	Starting new HTTP connection (4): 127.0.0.1:4723
DEBUG	2023-01-05 14:40:46,148	[remote_connection.py:308]	POST http://127.0.0.1:4723/wd/hub/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"platformName": "Android", "appium:deviceName": "127.0.0.1:21503", "appium:platformVersion": "7.1.2", "appium:appPackage": "com.tal.kaoyan", "appium:appActivity": "ui.activity.SplashActivity", "appium:noReset": false, "appium:unicodeKeyboard": true, "appium:resetKeyboard": true, "appium:automationName": "uiautomator2"}}}
DEBUG	2023-01-05 14:40:46,149	[connectionpool.py:232]	Starting new HTTP connection (1): 127.0.0.1:4723
DEBUG	2023-01-05 14:40:48,158	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:40:48,159	[connectionpool.py:813]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C26C86EF08>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:40:48,161	[connectionpool.py:232]	Starting new HTTP connection (2): 127.0.0.1:4723
DEBUG	2023-01-05 14:40:50,166	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:40:50,167	[connectionpool.py:813]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C26D4EA9C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:40:50,168	[connectionpool.py:232]	Starting new HTTP connection (3): 127.0.0.1:4723
DEBUG	2023-01-05 14:40:52,174	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:40:52,176	[connectionpool.py:813]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C26D505108>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:40:52,177	[connectionpool.py:232]	Starting new HTTP connection (4): 127.0.0.1:4723
DEBUG	2023-01-05 14:41:43,990	[remote_connection.py:308]	POST http://127.0.0.1:4723/wd/hub/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"platformName": "Android", "appium:deviceName": "127.0.0.1:21503", "appium:platformVersion": "7.1.2", "appium:appPackage": "com.tal.kaoyan", "appium:appActivity": "ui.activity.SplashActivity", "appium:noReset": false, "appium:unicodeKeyboard": true, "appium:resetKeyboard": true, "appium:automationName": "uiautomator2"}}}
DEBUG	2023-01-05 14:41:43,990	[connectionpool.py:232]	Starting new HTTP connection (1): 127.0.0.1:4723
DEBUG	2023-01-05 14:41:45,995	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:41:45,995	[connectionpool.py:813]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FDBA724388>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:41:45,995	[connectionpool.py:232]	Starting new HTTP connection (2): 127.0.0.1:4723
DEBUG	2023-01-05 14:41:47,998	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:41:47,998	[connectionpool.py:813]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FDBA73EC48>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:41:47,998	[connectionpool.py:232]	Starting new HTTP connection (3): 127.0.0.1:4723
DEBUG	2023-01-05 14:41:50,000	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:41:50,000	[connectionpool.py:813]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FDBA748508>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:41:50,000	[connectionpool.py:232]	Starting new HTTP connection (4): 127.0.0.1:4723
DEBUG	2023-01-05 14:46:21,489	[remote_connection.py:308]	POST http://127.0.0.1:4723/wd/hub/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"platformName": "Android", "appium:deviceName": "127.0.0.1:21503", "appium:platformVersion": "7.1.2", "appium:appPackage": "com.tal.kaoyan", "appium:appActivity": "ui.activity.SplashActivity", "appium:noReset": false, "appium:unicodeKeyboard": true, "appium:resetKeyboard": true, "appium:automationName": "uiautomator2"}}}
DEBUG	2023-01-05 14:46:21,490	[connectionpool.py:232]	Starting new HTTP connection (1): 127.0.0.1:4723
DEBUG	2023-01-05 14:46:23,495	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:46:23,495	[connectionpool.py:813]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000239E09BD408>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:46:23,495	[connectionpool.py:232]	Starting new HTTP connection (2): 127.0.0.1:4723
DEBUG	2023-01-05 14:46:25,498	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:46:25,498	[connectionpool.py:813]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000239E09DECC8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:46:25,498	[connectionpool.py:232]	Starting new HTTP connection (3): 127.0.0.1:4723
DEBUG	2023-01-05 14:46:27,501	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:46:27,501	[connectionpool.py:813]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000239E09E8588>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:46:27,501	[connectionpool.py:232]	Starting new HTTP connection (4): 127.0.0.1:4723
DEBUG	2023-01-05 14:46:49,552	[remote_connection.py:308]	POST http://127.0.0.1:4723/wd/hub/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"platformName": "Android", "appium:deviceName": "127.0.0.1:21503", "appium:platformVersion": "7.1.2", "appium:appPackage": "com.tal.kaoyan", "appium:appActivity": "ui.activity.SplashActivity", "appium:noReset": false, "appium:unicodeKeyboard": true, "appium:resetKeyboard": true, "appium:automationName": "uiautomator2"}}}
DEBUG	2023-01-05 14:46:49,553	[connectionpool.py:232]	Starting new HTTP connection (1): 127.0.0.1:4723
DEBUG	2023-01-05 14:46:51,556	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:46:51,556	[connectionpool.py:813]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C80A20D5C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:46:51,556	[connectionpool.py:232]	Starting new HTTP connection (2): 127.0.0.1:4723
DEBUG	2023-01-05 14:46:53,559	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:46:53,559	[connectionpool.py:813]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C80A236048>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:46:53,559	[connectionpool.py:232]	Starting new HTTP connection (3): 127.0.0.1:4723
DEBUG	2023-01-05 14:46:55,563	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:46:55,564	[connectionpool.py:813]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C80A2367C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:46:55,565	[connectionpool.py:232]	Starting new HTTP connection (4): 127.0.0.1:4723
DEBUG	2023-01-05 14:47:34,917	[remote_connection.py:308]	POST http://127.0.0.1:4723/wd/hub/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"platformName": "Android", "appium:deviceName": "127.0.0.1:21503", "appium:platformVersion": "7.1.2", "appium:appPackage": "com.tal.kaoyan", "appium:appActivity": "ui.activity.SplashActivity", "appium:noReset": false, "appium:unicodeKeyboard": true, "appium:resetKeyboard": true, "appium:automationName": "uiautomator2"}}}
DEBUG	2023-01-05 14:47:34,918	[connectionpool.py:232]	Starting new HTTP connection (1): 127.0.0.1:4723
DEBUG	2023-01-05 14:47:36,923	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:47:36,923	[connectionpool.py:813]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028D7522D188>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:47:36,923	[connectionpool.py:232]	Starting new HTTP connection (2): 127.0.0.1:4723
DEBUG	2023-01-05 14:48:19,330	[remote_connection.py:308]	POST http://127.0.0.1:4723/wd/hub/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"platformName": "Android", "appium:deviceName": "127.0.0.1:21503", "appium:platformVersion": "7.1.2", "appium:appPackage": "com.tal.kaoyan", "appium:appActivity": "ui.activity.SplashActivity", "appium:noReset": false, "appium:unicodeKeyboard": true, "appium:resetKeyboard": true, "appium:automationName": "uiautomator2"}}}
DEBUG	2023-01-05 14:48:19,331	[connectionpool.py:232]	Starting new HTTP connection (1): 127.0.0.1:4723
DEBUG	2023-01-05 14:48:21,337	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:48:21,338	[connectionpool.py:813]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021E56BF32C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:48:21,339	[connectionpool.py:232]	Starting new HTTP connection (2): 127.0.0.1:4723
DEBUG	2023-01-05 14:48:23,344	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:48:23,344	[connectionpool.py:813]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021E5753EB88>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:48:23,345	[connectionpool.py:232]	Starting new HTTP connection (3): 127.0.0.1:4723
DEBUG	2023-01-05 14:48:25,347	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:48:25,347	[connectionpool.py:813]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021E57547448>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:48:25,347	[connectionpool.py:232]	Starting new HTTP connection (4): 127.0.0.1:4723
DEBUG	2023-01-05 14:50:46,291	[remote_connection.py:308]	POST http://127.0.0.1:4723/wd/hub/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"platformName": "Android", "appium:deviceName": "127.0.0.1:21503", "appium:platformVersion": "7.1.2", "appium:appPackage": "com.tal.kaoyan", "appium:appActivity": "ui.activity.SplashActivity", "appium:noReset": false, "appium:unicodeKeyboard": true, "appium:resetKeyboard": true, "appium:automationName": "uiautomator2"}}}
DEBUG	2023-01-05 14:50:46,292	[connectionpool.py:232]	Starting new HTTP connection (1): 127.0.0.1:4723
DEBUG	2023-01-05 14:50:48,300	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:50:48,300	[connectionpool.py:813]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026AECC2D3C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:50:48,300	[connectionpool.py:232]	Starting new HTTP connection (2): 127.0.0.1:4723
DEBUG	2023-01-05 14:50:50,306	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:50:50,306	[connectionpool.py:813]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026AECC56088>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:50:50,307	[connectionpool.py:232]	Starting new HTTP connection (3): 127.0.0.1:4723
DEBUG	2023-01-05 14:50:52,310	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:50:52,310	[connectionpool.py:813]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026AECC56748>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:50:52,310	[connectionpool.py:232]	Starting new HTTP connection (4): 127.0.0.1:4723
DEBUG	2023-01-05 14:51:32,062	[remote_connection.py:308]	POST http://127.0.0.1:4723/wd/hub/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"platformName": "Android", "appium:deviceName": "127.0.0.1:21503", "appium:platformVersion": "7.1.2", "appium:appPackage": "com.tal.kaoyan", "appium:appActivity": "ui.activity.SplashActivity", "appium:noReset": false, "appium:unicodeKeyboard": true, "appium:resetKeyboard": true, "appium:automationName": "uiautomator2"}}}
DEBUG	2023-01-05 14:51:32,063	[connectionpool.py:232]	Starting new HTTP connection (1): 127.0.0.1:4723
DEBUG	2023-01-05 14:51:34,069	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:51:34,069	[connectionpool.py:813]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000011E74F0AEC8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:51:34,069	[connectionpool.py:232]	Starting new HTTP connection (2): 127.0.0.1:4723
DEBUG	2023-01-05 14:51:36,073	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:51:36,074	[connectionpool.py:813]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000011E74F5EE08>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:51:36,075	[connectionpool.py:232]	Starting new HTTP connection (3): 127.0.0.1:4723
DEBUG	2023-01-05 14:51:38,079	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 14:51:38,079	[connectionpool.py:813]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000011E74F676C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 14:51:38,079	[connectionpool.py:232]	Starting new HTTP connection (4): 127.0.0.1:4723
DEBUG	2023-01-05 15:25:55,688	[remote_connection.py:308]	POST http://127.0.0.1:4723/wd/hub/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"platformName": "Android", "appium:deviceName": "127.0.0.1:21503", "appium:platformVersion": "7.1.2", "appium:appPackage": "com.tal.kaoyan", "appium:appActivity": "ui.activity.SplashActivity", "appium:noReset": false, "appium:unicodeKeyboard": true, "appium:resetKeyboard": true, "appium:automationName": "uiautomator2"}}}
DEBUG	2023-01-05 15:25:55,688	[connectionpool.py:232]	Starting new HTTP connection (1): 127.0.0.1:4723
DEBUG	2023-01-05 15:25:57,692	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 15:25:57,692	[connectionpool.py:813]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001575AD143C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 15:25:57,692	[connectionpool.py:232]	Starting new HTTP connection (2): 127.0.0.1:4723
DEBUG	2023-01-05 15:25:59,695	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 15:25:59,696	[connectionpool.py:813]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001575AD2FCC8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 15:25:59,697	[connectionpool.py:232]	Starting new HTTP connection (3): 127.0.0.1:4723
DEBUG	2023-01-05 15:26:01,702	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 15:26:01,702	[connectionpool.py:813]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001575AD38588>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 15:26:01,702	[connectionpool.py:232]	Starting new HTTP connection (4): 127.0.0.1:4723
DEBUG	2023-01-05 15:31:15,625	[remote_connection.py:308]	POST http://127.0.0.1:4723/wd/hub/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"platformName": "Android", "appium:deviceName": "127.0.0.1:21503", "appium:platformVersion": "7.1.2", "appium:appPackage": "com.tal.kaoyan", "appium:appActivity": "ui.activity.SplashActivity", "appium:noReset": false, "appium:unicodeKeyboard": true, "appium:resetKeyboard": true, "appium:automationName": "uiautomator2"}}}
DEBUG	2023-01-05 15:31:15,625	[connectionpool.py:232]	Starting new HTTP connection (1): 127.0.0.1:4723
DEBUG	2023-01-05 15:31:17,630	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 15:31:17,630	[connectionpool.py:813]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000110CF29C548>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 15:31:17,630	[connectionpool.py:232]	Starting new HTTP connection (2): 127.0.0.1:4723
DEBUG	2023-01-05 15:31:19,635	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 15:31:19,635	[connectionpool.py:813]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000110CF2BFDC8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 15:31:19,635	[connectionpool.py:232]	Starting new HTTP connection (3): 127.0.0.1:4723
DEBUG	2023-01-05 15:31:21,638	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 15:31:21,638	[connectionpool.py:813]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000110CF2F8688>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 15:31:21,638	[connectionpool.py:232]	Starting new HTTP connection (4): 127.0.0.1:4723
DEBUG	2023-01-05 15:52:49,831	[remote_connection.py:308]	POST http://127.0.0.1:4723/wd/hub/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"platformName": "Android", "appium:deviceName": "127.0.0.1:21503", "appium:platformVersion": "7.1.2", "appium:appPackage": "com.tal.kaoyan", "appium:appActivity": "ui.activity.SplashActivity", "appium:noReset": false, "appium:unicodeKeyboard": true, "appium:resetKeyboard": true, "appium:automationName": "uiautomator2"}}}
DEBUG	2023-01-05 15:52:49,832	[connectionpool.py:232]	Starting new HTTP connection (1): 127.0.0.1:4723
DEBUG	2023-01-05 15:52:51,837	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 15:52:51,837	[connectionpool.py:813]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020A6A442AC8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 15:52:51,837	[connectionpool.py:232]	Starting new HTTP connection (2): 127.0.0.1:4723
DEBUG	2023-01-05 15:52:53,842	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 15:52:53,842	[connectionpool.py:813]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020A6AD8FD88>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 15:52:53,842	[connectionpool.py:232]	Starting new HTTP connection (3): 127.0.0.1:4723
DEBUG	2023-01-05 15:52:55,843	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 15:52:55,843	[connectionpool.py:813]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020A6AD98648>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 15:52:55,843	[connectionpool.py:232]	Starting new HTTP connection (4): 127.0.0.1:4723
DEBUG	2023-01-05 15:53:29,046	[remote_connection.py:308]	POST http://127.0.0.1:4723/wd/hub/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"platformName": "Android", "appium:deviceName": "127.0.0.1:21503", "appium:platformVersion": "7.1.2", "appium:appPackage": "com.tal.kaoyan", "appium:appActivity": "ui.activity.SplashActivity", "appium:noReset": false, "appium:unicodeKeyboard": true, "appium:resetKeyboard": true, "appium:automationName": "uiautomator2"}}}
DEBUG	2023-01-05 15:53:29,047	[connectionpool.py:232]	Starting new HTTP connection (1): 127.0.0.1:4723
DEBUG	2023-01-05 15:53:31,056	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 15:53:31,056	[connectionpool.py:813]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FA24D8D288>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 15:53:31,056	[connectionpool.py:232]	Starting new HTTP connection (2): 127.0.0.1:4723
DEBUG	2023-01-05 15:53:33,059	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 15:53:33,059	[connectionpool.py:813]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FA24DAFD08>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 15:53:33,059	[connectionpool.py:232]	Starting new HTTP connection (3): 127.0.0.1:4723
DEBUG	2023-01-05 15:53:35,062	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 15:53:35,062	[connectionpool.py:813]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FA24DB85C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 15:53:35,062	[connectionpool.py:232]	Starting new HTTP connection (4): 127.0.0.1:4723
DEBUG	2023-01-05 16:12:31,256	[remote_connection.py:308]	POST http://127.0.0.1:4723/wd/hub/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"platformName": "Android", "appium:deviceName": "127.0.0.1:21503", "appium:platformVersion": "7.1.2", "appium:appPackage": "com.tal.kaoyan", "appium:appActivity": "ui.activity.SplashActivity", "appium:noReset": false, "appium:unicodeKeyboard": true, "appium:resetKeyboard": true, "appium:automationName": "uiautomator2"}}}
DEBUG	2023-01-05 16:12:31,256	[connectionpool.py:232]	Starting new HTTP connection (1): 127.0.0.1:4723
DEBUG	2023-01-05 16:12:33,263	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 16:12:33,263	[connectionpool.py:813]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A82C2A9748>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 16:12:33,263	[connectionpool.py:232]	Starting new HTTP connection (2): 127.0.0.1:4723
DEBUG	2023-01-05 16:12:35,268	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 16:12:35,268	[connectionpool.py:813]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A82C2E10C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 16:12:35,268	[connectionpool.py:232]	Starting new HTTP connection (3): 127.0.0.1:4723
DEBUG	2023-01-05 16:12:37,273	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 16:12:37,273	[connectionpool.py:813]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A82C2E18C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 16:12:37,273	[connectionpool.py:232]	Starting new HTTP connection (4): 127.0.0.1:4723
DEBUG	2023-01-05 16:17:05,564	[remote_connection.py:308]	POST http://127.0.0.1:4723/wd/hub/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"platformName": "Android", "appium:deviceName": "127.0.0.1:21503", "appium:platformVersion": "7.1.2", "appium:appPackage": "com.tal.kaoyan", "appium:appActivity": "ui.activity.SplashActivity", "appium:noReset": false, "appium:unicodeKeyboard": true, "appium:resetKeyboard": true, "appium:automationName": "uiautomator2"}}}
DEBUG	2023-01-05 16:17:05,565	[connectionpool.py:232]	Starting new HTTP connection (1): 127.0.0.1:4723
DEBUG	2023-01-05 16:17:07,571	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 16:17:07,571	[connectionpool.py:813]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018DE32C9488>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 16:17:07,571	[connectionpool.py:232]	Starting new HTTP connection (2): 127.0.0.1:4723
DEBUG	2023-01-05 16:17:09,574	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 16:17:09,574	[connectionpool.py:813]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018DE32EDD48>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 16:17:09,574	[connectionpool.py:232]	Starting new HTTP connection (3): 127.0.0.1:4723
DEBUG	2023-01-05 16:57:46,479	[remote_connection.py:308]	POST http://127.0.0.1:4723/wd/hub/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"platformName": "Android", "appium:deviceName": "127.0.0.1:21503", "appium:platformVersion": "7.1.2", "appium:appPackage": "com.tal.kaoyan", "appium:appActivity": "ui.activity.SplashActivity", "appium:noReset": false, "appium:unicodeKeyboard": true, "appium:resetKeyboard": true, "appium:automationName": "uiautomator2"}}}
DEBUG	2023-01-05 16:57:46,479	[connectionpool.py:232]	Starting new HTTP connection (1): 127.0.0.1:4723
DEBUG	2023-01-05 16:57:48,495	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 16:57:48,496	[connectionpool.py:813]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000290164C9808>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 16:57:48,496	[connectionpool.py:232]	Starting new HTTP connection (2): 127.0.0.1:4723
DEBUG	2023-01-05 16:57:50,501	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 16:57:50,501	[connectionpool.py:813]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000029016502108>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 16:57:50,501	[connectionpool.py:232]	Starting new HTTP connection (3): 127.0.0.1:4723
DEBUG	2023-01-05 16:57:52,512	[retry.py:594]	Incremented Retry for (url='/wd/hub/session'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
WARNING	2023-01-05 16:57:52,512	[connectionpool.py:813]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000029016502988>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG	2023-01-05 16:57:52,512	[connectionpool.py:232]	Starting new HTTP connection (4): 127.0.0.1:4723
